INCLUDEPATH += $$PWD/include

SOURCES += \
    $$PWD/src/collision/b2_broad_phase.cpp \
    $$PWD/src/collision/b2_chain_shape.cpp \
    $$PWD/src/collision/b2_circle_shape.cpp \
    $$PWD/src/collision/b2_collide_circle.cpp \
    $$PWD/src/collision/b2_collide_edge.cpp \
    $$PWD/src/collision/b2_collide_polygon.cpp \
    $$PWD/src/collision/b2_collision.cpp \
    $$PWD/src/collision/b2_distance.cpp \
    $$PWD/src/collision/b2_dynamic_tree.cpp \
    $$PWD/src/collision/b2_edge_shape.cpp \
    $$PWD/src/collision/b2_polygon_shape.cpp \
    $$PWD/src/collision/b2_time_of_impact.cpp \
    $$PWD/src/common/b2_block_allocator.cpp \
    $$PWD/src/common/b2_draw.cpp \
    $$PWD/src/common/b2_math.cpp \
    $$PWD/src/common/b2_settings.cpp \
    $$PWD/src/common/b2_stack_allocator.cpp \
    $$PWD/src/common/b2_timer.cpp \
    $$PWD/src/dynamics/b2_body.cpp \
    $$PWD/src/dynamics/b2_chain_circle_contact.cpp \
    $$PWD/src/dynamics/b2_chain_polygon_contact.cpp \
    $$PWD/src/dynamics/b2_circle_contact.cpp \
    $$PWD/src/dynamics/b2_contact.cpp \
    $$PWD/src/dynamics/b2_contact_manager.cpp \
    $$PWD/src/dynamics/b2_contact_solver.cpp \
    $$PWD/src/dynamics/b2_distance_joint.cpp \
    $$PWD/src/dynamics/b2_edge_circle_contact.cpp \
    $$PWD/src/dynamics/b2_edge_polygon_contact.cpp \
    $$PWD/src/dynamics/b2_fixture.cpp \
    $$PWD/src/dynamics/b2_friction_joint.cpp \
    $$PWD/src/dynamics/b2_gear_joint.cpp \
    $$PWD/src/dynamics/b2_island.cpp \
    $$PWD/src/dynamics/b2_joint.cpp \
    $$PWD/src/dynamics/b2_motor_joint.cpp \
    $$PWD/src/dynamics/b2_mouse_joint.cpp \
    $$PWD/src/dynamics/b2_polygon_circle_contact.cpp \
    $$PWD/src/dynamics/b2_polygon_contact.cpp \
    $$PWD/src/dynamics/b2_prismatic_joint.cpp \
    $$PWD/src/dynamics/b2_pulley_joint.cpp \
    $$PWD/src/dynamics/b2_revolute_joint.cpp \
    $$PWD/src/dynamics/b2_weld_joint.cpp \
    $$PWD/src/dynamics/b2_wheel_joint.cpp \
    $$PWD/src/dynamics/b2_world.cpp \
    $$PWD/src/dynamics/b2_world_callbacks.cpp \
    $$PWD/src/rope/b2_rope.cpp

HEADERS += \
    $$PWD/include/box2d/b2_api.h \
    $$PWD/include/box2d/b2_block_allocator.h \
    $$PWD/include/box2d/b2_body.h \
    $$PWD/include/box2d/b2_broad_phase.h \
    $$PWD/include/box2d/b2_chain_shape.h \
    $$PWD/include/box2d/b2_circle_shape.h \
    $$PWD/include/box2d/b2_collision.h \
    $$PWD/include/box2d/b2_common.h \
    $$PWD/include/box2d/b2_contact.h \
    $$PWD/include/box2d/b2_contact_manager.h \
    $$PWD/include/box2d/b2_distance.h \
    $$PWD/include/box2d/b2_distance_joint.h \
    $$PWD/include/box2d/b2_draw.h \
    $$PWD/include/box2d/b2_dynamic_tree.h \
    $$PWD/include/box2d/b2_edge_shape.h \
    $$PWD/include/box2d/b2_fixture.h \
    $$PWD/include/box2d/b2_friction_joint.h \
    $$PWD/include/box2d/b2_gear_joint.h \
    $$PWD/include/box2d/b2_growable_stack.h \
    $$PWD/include/box2d/b2_joint.h \
    $$PWD/include/box2d/b2_math.h \
    $$PWD/include/box2d/b2_motor_joint.h \
    $$PWD/include/box2d/b2_mouse_joint.h \
    $$PWD/include/box2d/b2_polygon_shape.h \
    $$PWD/include/box2d/b2_prismatic_joint.h \
    $$PWD/include/box2d/b2_pulley_joint.h \
    $$PWD/include/box2d/b2_revolute_joint.h \
    $$PWD/include/box2d/b2_rope.h \
    $$PWD/include/box2d/b2_settings.h \
    $$PWD/include/box2d/b2_shape.h \
    $$PWD/include/box2d/b2_stack_allocator.h \
    $$PWD/include/box2d/b2_time_of_impact.h \
    $$PWD/include/box2d/b2_time_step.h \
    $$PWD/include/box2d/b2_timer.h \
    $$PWD/include/box2d/b2_types.h \
    $$PWD/include/box2d/b2_weld_joint.h \
    $$PWD/include/box2d/b2_wheel_joint.h \
    $$PWD/include/box2d/b2_world.h \
    $$PWD/include/box2d/b2_world_callbacks.h \
    $$PWD/include/box2d/box2d.h \
    $$PWD/src/dynamics/b2_chain_circle_contact.h \
    $$PWD/src/dynamics/b2_chain_polygon_contact.h \
    $$PWD/src/dynamics/b2_circle_contact.h \
    $$PWD/src/dynamics/b2_contact_solver.h \
    $$PWD/src/dynamics/b2_edge_circle_contact.h \
    $$PWD/src/dynamics/b2_edge_polygon_contact.h \
    $$PWD/src/dynamics/b2_island.h \
    $$PWD/src/dynamics/b2_polygon_circle_contact.h \
    $$PWD/src/dynamics/b2_polygon_contact.h
